import moment from 'moment';
import { UsersTest } from '../../../utils/type';

export const UserTestingData: UsersTest[] = [
  {
    key: '1',
    name: 'Nguyen Thi Hai',
    numberPhone: '0956128765',
    email: 'example1@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'EMS',
    startDate: moment('10-29-2020').format('MM-DD-YYYY'),
  },
  {
    key: '2',
    name: 'Nguyen Van Toan',
    numberPhone: '0956128765',
    email: 'example2@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'EMS',
    startDate: moment('10-18-2021').format('MM-DD-YYYY'),
  },
  {
    key: '3',
    name: 'Nguyen Chi Thanh',
    numberPhone: '0956128765',
    email: 'example3@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'Storage',
    startDate: moment('10-07-2022').format('MM-DD-YYYY'),
  },
  {
    key: '4',
    name: 'Vo Van Thuong',
    numberPhone: '0956128765',
    email: 'example4@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'EMS',
    startDate: moment('10-19-2023').format('MM-DD-YYYY'),
  },
  {
    key: '5',
    name: 'Doraemon',
    numberPhone: '0956128765',
    email: 'example5@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'EMS',
    startDate: moment('01-10-2024').format('MM-DD-YYYY'),
  },
  {
    key: '6',
    name: 'Songoku',
    numberPhone: '0956128765',
    email: 'example6@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'EMS',
    startDate: moment('03-10-2022').format('MM-DD-YYYY'),
  },
  {
    key: '7',
    name: 'Vo Tuan Anh',
    numberPhone: '0956128765',
    email: 'example7@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'Storage',
    startDate: moment('04-15-2018').format('MM-DD-YYYY'),
  },
  {
    key: '8',
    name: 'Khang Tuat',
    numberPhone: '0956128765',
    email: 'example8@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'Storage',
    startDate: moment('04-17-2021').format('MM-DD-YYYY'),
  },
  {
    key: '9',
    name: 'Thu Hien',
    numberPhone: '0956128765',
    email: 'example9@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'EMS',
    startDate: moment('04-11-2022').format('MM-DD-YYYY'),
  },
  {
    key: '10',
    name: 'Tran Thu Hoai',
    numberPhone: '0956128765',
    email: 'example10@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'Storage',
    startDate: moment('09-24-2023').format('MM-DD-YYYY'),
  },
  {
    key: '11',
    name: 'Tran Thu Thuy',
    numberPhone: '0956128765',
    email: 'example11@gmail.com',
    organization: 'Mind Smart IOT',
    service: 'Storage',
    startDate: moment('01-22-2023').format('MM-DD-YYYY'),
  },
];
