import moment from 'moment';
import { DeviceTypeList } from '../../../utils/device';

export const deviceTypeData: DeviceTypeList[] = [
  {
    key: '1',
    name: 'Energy Device 1CT',
    gateWay: true,
    model: 'HTENG-300',
    createdAt: moment('05-20-2020', 'MM-DD-YYYY').format('L'),
    deviceNumber: 412,
    description: 'Thiết bị đo năng lượng kẹp dây 1 ct',
    image: 'https://pbs.twimg.com/media/FKNJfRMXsAgdSck.jpg:large',
  },
  {
    key: '2',
    name: 'Energy Device 1CT',
    gateWay: true,
    model: 'HTENG-300',
    createdAt: moment('05-20-2020', 'MM-DD-YYYY').format('L'),
    deviceNumber: 900,
    description: 'Thiết bị đo năng lượng kẹp dây 1 ct',
    image: 'https://pbs.twimg.com/media/FKNJfRMXsAgdSck.jpg:large',
  },
  {
    key: '3',
    name: 'Energy Device 1CT',
    gateWay: true,
    model: 'HTENG-300',
    createdAt: moment('05-20-2020', 'MM-DD-YYYY').format('L'),
    deviceNumber: 352,
    description: 'Thiết bị đo năng lượng kẹp dây 1 ct',
    image: 'https://pbs.twimg.com/media/FKNJfRMXsAgdSck.jpg:large',
  },
  {
    key: '4',
    name: 'Energy Device 1CT',
    gateWay: true,
    model: 'HTENG-300',
    createdAt: moment('05-20-2020', 'MM-DD-YYYY').format('L'),
    deviceNumber: 231,
    description: 'Thiết bị đo năng lượng kẹp dây 1 ct',
    image: 'https://pbs.twimg.com/media/FKNJfRMXsAgdSck.jpg:large',
  },
  {
    key: '5',
    name: 'Energy Device 1CT',
    gateWay: false,
    model: 'HTENG-300',
    createdAt: moment('05-20-2020', 'MM-DD-YYYY').format('L'),
    deviceNumber: 323,
    description: 'Thiết bị đo năng lượng kẹp dây 1 ct',
    image: 'https://pbs.twimg.com/media/FKNJfRMXsAgdSck.jpg:large',
  },
  {
    key: '6',
    name: 'Energy Device 1CT',
    gateWay: true,
    model: 'HTENG-300',
    createdAt: moment('05-20-2020', 'MM-DD-YYYY').format('L'),
    deviceNumber: 564,
    description: 'Thiết bị đo năng lượng kẹp dây 1 ct',
    image: 'https://pbs.twimg.com/media/FKNJfRMXsAgdSck.jpg:large',
  },
];
